from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication
from PyQt6.QtCore import Qt

class MainWindowApp(object):

    def setupUi(self, MainWindow: QMainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 586)
        MainWindow.setWindowFlag(Qt.WindowType.FramelessWindowHint, False)
        MainWindow.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 50, 851, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(140, 30, 131, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit.setGeometry(QtCore.QRect(50, 80, 161, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 140, 161, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 170, 161, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 80, 161, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 110, 161, 22))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_8.setGeometry(QtCore.QRect(220, 140, 161, 22))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_9.setGeometry(QtCore.QRect(50, 220, 161, 22))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_10.setGeometry(QtCore.QRect(50, 250, 161, 22))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_6.setGeometry(QtCore.QRect(170, 290, 91, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit = QtWidgets.QTextEdit(parent=self.page)
        self.textEdit.setGeometry(QtCore.QRect(490, 190, 201, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(490, 30, 101, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_16.setGeometry(QtCore.QRect(490, 130, 201, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_11.setGeometry(QtCore.QRect(490, 70, 131, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton = QtWidgets.QPushButton(parent=self.page)
        self.pushButton.setGeometry(QtCore.QRect(550, 270, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_12.setGeometry(QtCore.QRect(490, 100, 201, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_17.setGeometry(QtCore.QRect(490, 160, 201, 22))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.comboBox = QtWidgets.QComboBox(parent=self.page)
        self.comboBox.setGeometry(QtCore.QRect(220, 110, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.page)
        self.comboBox_2.setGeometry(QtCore.QRect(310, 110, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_13.setGeometry(QtCore.QRect(220, 220, 161, 22))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_14.setGeometry(QtCore.QRect(220, 250, 161, 22))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 370, 113, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 370, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setGeometry(QtCore.QRect(50, 340, 131, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 170, 161, 24))
        self.pushButton_9.setObjectName("pushButton_9")
        self.comboBox_12 = QtWidgets.QComboBox(parent=self.page)
        self.comboBox_12.setGeometry(QtCore.QRect(630, 70, 61, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_8 = QtWidgets.QLabel(parent=self.page_4)
        self.label_8.setGeometry(QtCore.QRect(120, 50, 81, 16))
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.lineEdit_33 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_33.setGeometry(QtCore.QRect(230, 230, 161, 22))
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_34.setGeometry(QtCore.QRect(230, 200, 161, 22))
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_35.setGeometry(QtCore.QRect(60, 130, 161, 22))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.comboBox_9 = QtWidgets.QComboBox(parent=self.page_3)
        self.comboBox_9.setGeometry(QtCore.QRect(320, 100, 69, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_13.setGeometry(QtCore.QRect(260, 350, 91, 24))
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_36 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_36.setGeometry(QtCore.QRect(60, 160, 161, 22))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.comboBox_10 = QtWidgets.QComboBox(parent=self.page_3)
        self.comboBox_10.setGeometry(QtCore.QRect(230, 100, 69, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.lineEdit_37 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_37.setGeometry(QtCore.QRect(60, 200, 161, 22))
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_38.setGeometry(QtCore.QRect(60, 230, 161, 22))
        self.lineEdit_38.setText("")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_39.setGeometry(QtCore.QRect(60, 100, 161, 22))
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_40.setGeometry(QtCore.QRect(60, 70, 161, 22))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_41.setGeometry(QtCore.QRect(230, 70, 161, 22))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(parent=self.page_3)
        self.lineEdit_42.setGeometry(QtCore.QRect(230, 130, 161, 22))
        self.lineEdit_42.setText("")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_14.setGeometry(QtCore.QRect(100, 350, 91, 24))
        self.pushButton_14.setObjectName("pushButton_14")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.page_3)
        self.textEdit_3.setGeometry(QtCore.QRect(60, 260, 331, 71))
        self.textEdit_3.setObjectName("textEdit_3")
        self.comboBox_11 = QtWidgets.QComboBox(parent=self.page_3)
        self.comboBox_11.setGeometry(QtCore.QRect(230, 160, 161, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_7 = QtWidgets.QLabel(parent=self.page_3)
        self.label_7.setGeometry(QtCore.QRect(330, 20, 151, 16))
        self.label_7.setObjectName("label_7")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.page_3)
        self.graphicsView.setGeometry(QtCore.QRect(410, 70, 281, 231))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_15.setGeometry(QtCore.QRect(410, 310, 91, 24))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_18.setGeometry(QtCore.QRect(160, 390, 121, 24))
        self.pushButton_18.setObjectName("pushButton_18")
        self.stackedWidget.addWidget(self.page_3)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_6)
        self.tableWidget.setGeometry(QtCore.QRect(20, 50, 531, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.page_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(570, 50, 271, 351))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.page_6)
        self.comboBox_7.setGeometry(QtCore.QRect(20, 20, 69, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.lineEdit_31 = QtWidgets.QLineEdit(parent=self.page_6)
        self.lineEdit_31.setGeometry(QtCore.QRect(100, 20, 113, 22))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.page_6)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 20, 75, 24))
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox_8 = QtWidgets.QComboBox(parent=self.page_6)
        self.comboBox_8.setGeometry(QtCore.QRect(570, 20, 69, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.lineEdit_32 = QtWidgets.QLineEdit(parent=self.page_6)
        self.lineEdit_32.setGeometry(QtCore.QRect(650, 20, 113, 22))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.page_6)
        self.pushButton_11.setGeometry(QtCore.QRect(770, 20, 75, 24))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.page_6)
        self.pushButton_16.setGeometry(QtCore.QRect(590, 420, 101, 24))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.page_6)
        self.pushButton_17.setGeometry(QtCore.QRect(710, 420, 101, 24))
        self.pushButton_17.setObjectName("pushButton_17")
        self.stackedWidget.addWidget(self.page_6)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 110, 141, 321))
        self.widget.setObjectName("widget")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 40, 121, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 70, 121, 24))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 100, 121, 24))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 130, 121, 24))
        self.pushButton_21.setObjectName("pushButton_21")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionConfigura_es_Gerais = QtGui.QAction(parent=MainWindow)
        self.actionConfigura_es_Gerais.setObjectName("actionConfigura_es_Gerais")
        self.actionSair = QtGui.QAction(parent=MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.pushButton_4.clicked.connect(self.goToAnimaisCadastro)
        self.pushButton_19.clicked.connect(self.goToConfiguracoes)
        self.pushButton_20.clicked.connect(self.goToRelatorios)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cadastrar Novo Animal"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Cod do Chip"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Cod Chip do Pai"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Cod Chip da Mae"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Nascimento"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Pelagem"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "CPF do Criador"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "CPF do Proprietário"))
        self.pushButton_6.setText(_translate("MainWindow", "Salvar"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Observações Gerias"))
        self.label_2.setText(_translate("MainWindow", "Cadastro Terceiros"))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "Celular"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "CPF ou CNPJ"))
        self.pushButton.setText(_translate("MainWindow", "Adicionar"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEdit_17.setPlaceholderText(_translate("MainWindow", "Cidade"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "Preço de Compra"))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "Preço de Venda"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.label_3.setText(_translate("MainWindow", "Rastreio Genealogico"))
        self.pushButton_9.setText(_translate("MainWindow", "Adicionar Imagens"))
        self.label_8.setText(_translate("MainWindow", "Alterar Usuario"))
        self.lineEdit_33.setPlaceholderText(_translate("MainWindow", "Preço de Venda"))
        self.lineEdit_34.setPlaceholderText(_translate("MainWindow", "Preço de Compra"))
        self.lineEdit_35.setPlaceholderText(_translate("MainWindow", "Cod Chip do Pai"))
        self.pushButton_13.setText(_translate("MainWindow", "Excluir"))
        self.lineEdit_36.setPlaceholderText(_translate("MainWindow", "Cod Chip da Mae"))
        self.lineEdit_37.setPlaceholderText(_translate("MainWindow", "CPF do Criador"))
        self.lineEdit_38.setPlaceholderText(_translate("MainWindow", "CPF do Proprietário"))
        self.lineEdit_39.setPlaceholderText(_translate("MainWindow", "Nascimento"))
        self.lineEdit_40.setPlaceholderText(_translate("MainWindow", "Cod do Chip"))
        self.lineEdit_41.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEdit_42.setPlaceholderText(_translate("MainWindow", "Pelagem"))
        self.pushButton_14.setText(_translate("MainWindow", "Salvar"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "Escreva as observações da alteração. "))
        self.label_7.setText(_translate("MainWindow", "Alterar/Excluir Animal"))
        self.pushButton_15.setText(_translate("MainWindow", "Add Fotos"))
        self.pushButton_18.setText(_translate("MainWindow", "Rastreio Genealogico"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "Backup Animais"))
        self.pushButton_17.setText(_translate("MainWindow", "Backup Terceiros"))
        self.pushButton_4.setText(_translate("MainWindow", "Cadastro Animais"))
        self.pushButton_19.setText(_translate("MainWindow", "Configurações"))
        self.pushButton_20.setText(_translate("MainWindow", "Relatorios"))
        self.pushButton_21.setText(_translate("MainWindow", "Dashboards"))
        self.actionConfigura_es_Gerais.setText(_translate("MainWindow", "Configurações Gerais"))
        self.actionSair.setText(_translate("MainWindow", "Sair "))

    def goToAnimaisCadastro(self):
        self.stackedWidget.setCurrentIndex(0)
    
    def goToRelatorios(self):
        self.stackedWidget.setCurrentIndex(3)

    def goToConfiguracoes(self):
        self.stackedWidget.setCurrentIndex(1)

